### ISSUE TITLE
问题：如何通过本地代理进行请求转发呢

### ISSUE THREAD

**Issue by Ikaros-521** [erictik/midjourney-ui#13]
如题
跑的是v2ray，代理地址：http://127.0.0.1:10809
尝试改过UI内的request下的程序无果，是不是要改midjourney-api内的源码呢，写不来
![image](https://github.com/erictik/midjourney-ui/assets/40910637/30f06c20-2d97-400e-a9ae-fbb8a4412163)

**Comment by zcpua** [comment]
开启增强模式吧

**Comment by Ikaros-521** [comment]
> v2ray

开不了增强模式，服务器有其他服务要跑，这该咋办呀

**Comment by zcpua** [comment]
那就用docker，docker里面开增强模式

**Comment by Ikaros-521** [comment]
> 那就用docker，docker里面开增强模式

啊这，docker里面挂v2r吗，不止midj一个要用，其他部分服务也要用，这样搞不会有影响吗，docker我也用不来
![image](https://github.com/erictik/midjourney-ui/assets/40910637/1727f5a5-8930-47c9-bbc6-64b87e32084b)

**Comment by Ikaros-521** [comment]
有直接改源码就能实现的方法吗，大佬可以点播点播吗，源码这块我可以改

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/blob/main/src/midjourney.ts
https://github.com/erictik/midjourney-api/blob/main/src/midjourney.message.ts

**Comment by Ikaros-521** [comment]
> https://github.com/erictik/midjourney-api/blob/main/src/midjourney.ts https://github.com/erictik/midjourney-api/blob/main/src/midjourney.message.ts

是主要改请求这块吧
```
  protected async interactions(
    payload: any,
    callback?: (result: number) => void
  ) {
    try {
      const headers = {
        "Content-Type": "application/json",
        Authorization: this.SalaiToken,
      };
      const response = await fetch("https://discord.com/api/v9/interactions", {
        method: "POST",
        body: JSON.stringify(payload),
        headers: headers,
      });
      callback && callback(response.status);
      //discord api rate limit
      await sleep(950);
      return response.status;
    } catch (error) {
      console.log(error);
      callback && callback(500);
    }
  }
```

**Comment by zcpua** [comment]
对啊

**Comment by Ikaros-521** [comment]
> protected async interactions(
>     payload: any,
>     callback?: (result: number) => void
>   ) {
>     try {
>       const headers = {
>         "Content-Type": "application/json",
>         Authorization: this.SalaiToken,
>       };
>       const response = await fetch("https://discord.com/api/v9/interactions", {
>         method: "POST",
>         body: JSON.stringify(payload),
>         headers: headers,
>       });
>       callback && callback(response.status);
>       //discord api rate limit
>       await sleep(950);
>       return response.status;
>     } catch (error) {
>       console.log(error);
>       callback && callback(500);
>     }

好的，感谢大佬。
不过还有个问题，就是现在项目是直接npm安装的api，我要改的话，直接去项目路径的node_里面改吗，我看里面和原项目不一样，是做了什么打包转换操作吗。
我要改的话，应该怎么进行呢

**Comment by Ikaros-521** [comment]
是不是直接改api项目的源码，然后重新执行 `npm i midjourney` 这个去做覆盖呢
还是说 执行 `npm install`做安装呢（问题可能很蠢，但是真不会
![image](https://github.com/erictik/midjourney-ui/assets/40910637/3ee24e86-a2c0-41bb-b8bf-1b43da56ad5d)
）

**Comment by zcpua** [comment]
你可以fork 仓库 然后 修改一下代码  用你的库代替 midjourney   
npm i https://github.com/user_name/node_project_name  
或者  在 node_model  里面搜索替换 discord 链接都行

**Comment by Ikaros-521** [comment]
> 你可以fork 仓库 然后 修改一下代码 用你的库代替 midjourney npm i https://github.com/user_name/node_project_name 或者 在 node_model 里面搜索替换 discord 链接都行

![QQ图片20230512155023](https://github.com/erictik/midjourney-ui/assets/40910637/a99eef6f-1d08-4fbd-82c1-b762906a8152)

![image](https://github.com/erictik/midjourney-ui/assets/40910637/59091e93-975c-4777-a0ac-1bf9f3bbc559)

**Comment by ooweigan** [comment]
![image](https://github.com/erictik/midjourney-ui/assets/129486757/dfed475c-abe8-4081-821f-f6a683029417)
d大佬这是啥错啊

**Comment by Ikaros-521** [comment]
@zcpua 大佬，我这换了台win的海外服务器，配置了`.env`，现在报错401，这是为什么呢（ps：vercel也寄了 ）
3个配置项也是新获取的
![image](https://github.com/erictik/midjourney-ui/assets/40910637/e1905840-1bb1-4efc-a47a-a5496266da57)

**Comment by zcpua** [comment]
https://www.androidauthority.com/get-discord-token-3149920/

**Comment by Ikaros-521** [comment]
> https://www.androidauthority.com/get-discord-token-3149920/

token新获取的 没问题，难道必须是/api的auth吗

**Comment by Ikaros-521** [comment]
> https://www.androidauthority.com/get-discord-token-3149920/

确认过了auth是对的，大佬你部署的站点也挂了

**Comment by zcpua** [comment]
因为这个账号的api 要给同事使用就把 demo 停掉了

只有特别少的人出现401  个人感觉很有可能还是  authorization 不对吧  有可能过期了

**Comment by Ikaros-521** [comment]
> 因为这个账号的api 要给同事使用就把 demo 停掉了
> 
> 只有特别少的人出现401 个人感觉很有可能还是 authorization 不对吧 有可能过期了

啊这，新获取的，还是不行，完蛋
![image](https://github.com/erictik/midjourney-ui/assets/40910637/10f5f581-5b26-44c4-91ee-08f1f053e5c8)

**Comment by Ikaros-521** [comment]
用这个项目是可以拿到响应的
https://github.com/George-iam/Midjourney_api

**Comment by zcpua** [comment]
discord   频道内用 /info 
![image](https://github.com/erictik/midjourney-ui/assets/34678575/9c33a3d4-5001-448d-b849-12a764d2b5cd)

**Comment by Ikaros-521** [comment]
还是不行，oh no

> discord 频道内用 /info ![image](https://user-images.githubusercontent.com/34678575/238130250-9c33a3d4-5001-448d-b849-12a764d2b5cd.png)

![image](https://github.com/erictik/midjourney-ui/assets/40910637/e9e69128-9511-4b83-a8d0-1cab687cd331)
![image](https://github.com/erictik/midjourney-ui/assets/40910637/d9bba33f-c599-4ff0-bd81-b35741217744)

**Comment by zcpua** [comment]
有可能是 session ID 的 问题  明天我加上看看

**Comment by Ikaros-521** [comment]
> 有可能是 session ID 的 问题 明天我加上看看

大佬真好
![image](https://github.com/erictik/midjourney-ui/assets/40910637/352b50f2-5e21-470e-9794-3a6faedde85d)

**Comment by zcpua** [comment]
设置 sessionID 试一下呢

**Comment by Ikaros-521** [comment]
> 设置 sessionID 试一下呢

我试试

**Comment by Ikaros-521** [comment]
> 设置 sessionID 试一下呢

![image](https://github.com/erictik/midjourney-ui/assets/40910637/4973973e-965b-452c-945b-9dc112ffffdd)
还是401 自闭了

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api 运行 example 试一试呢

**Comment by Ikaros-521** [comment]
> https://github.com/erictik/midjourney-api 运行 example 试一试呢

我试试

**Comment by zcpua** [comment]
npx tsx example/message.ts

**Comment by Ikaros-521** [comment]
> npx tsx example/message.ts
难绷
![image](https://github.com/erictik/midjourney-ui/assets/40910637/c44f21a3-6655-4c11-b19d-4fb965444153)

**Comment by zcpua** [comment]
.env 加上引号试试吧
```
SALAI_TOKEN="MTAxx-.x-x"
```

**Comment by Ikaros-521** [comment]
> .env 加上引号试试吧
> 
> ```
> SALAI_TOKEN="MTAxx-.x-x"
> ```
不加，加""，加[]都试过了，寄
![image](https://github.com/erictik/midjourney-ui/assets/40910637/d01f220b-e790-4ce4-8f1c-3e913ab9b8c3)

**Comment by zcpua** [comment]
run  
npx tsx example/message.ts
试试呢

**Comment by Ikaros-521** [comment]
> npx tsx example/message.ts

run命令不存在吧，跑不了（哦 没事了）

**Comment by Ikaros-521** [comment]
> run npx tsx example/message.ts 试试呢

![image](https://github.com/erictik/midjourney-ui/assets/40910637/5b91da45-3cba-4a4b-8785-83a23caee665)

**Comment by Ikaros-521** [comment]
看着还是鉴权没过的样子
见鬼了

**Comment by zcpua** [comment]
如果同一个token python 的代码可以用 node 的 不可以用 那就离谱了

**Comment by zcpua** [comment]
> 如果同一个token python 的代码可以用 node 的 不可以用 那就离谱了

要不就 把配置直接写到 example/message.ts 这个文件里面试试呢

**Comment by Ikaros-521** [comment]
> 如果同一个token python 的代码可以用 node 的 不可以用 那就离谱了

对呀，就离谱

**Comment by Ikaros-521** [comment]
> > 如果同一个token python 的代码可以用 node 的 不可以用 那就离谱了
> 
> 要不就 把配置直接写到 example/message.ts 这个文件里面试试呢

woc 成了，难不成配置读取的不对

**Comment by Ikaros-521** [comment]
![image](https://github.com/erictik/midjourney-ui/assets/40910637/eab509b4-a4ab-44cd-8fc6-df9ba916e77a)
wo我看日志打印的配置路径没毛病的呀

**Comment by zcpua** [comment]
那再试试吧 最起码 vercel 上不会有问题吧

**Comment by Ikaros-521** [comment]
> 那再试试吧 最起码 vercel 上不会有问题吧

vercel上也有问题
![}7JNTURQLB@5(J7AV4_MHO0](https://github.com/erictik/midjourney-ui/assets/40910637/99a93909-3ded-4685-a3dd-76c635278c56)

**Comment by Ikaros-521** [comment]
省流 win下运行时，手动设置环境
```
set SALAI_TOKEN=xxxx.xxxxxxxxx
set SERVER_ID=110111111204
set CHANNEL_ID=11041111113207
set SESSION_ID=b1111111111113
npm run dev
```
