### ISSUE TITLE
生成照片不能显示

### ISSUE THREAD

**Issue by china-Charles-yang** [erictik/midjourney-ui#17]
因为网络限制，src="https://cdn.discordapp.com/attachments/*/nd_the_Ye_18a33ae1-6b56-49a9-9755-6c9d3510f7cf.png"这类照片不能访问，这个怎么处理

**Comment by zcpua** [comment]
#12 
可以自己配置反向代理

**Comment by china-Charles-yang** [comment]
你这个怎么配置反向代理呀
