### ISSUE TITLE
违禁词处理

### ISSUE THREAD

**Issue by yklingaOa** [erictik/midjourney-ui#22]
是否对违禁词，有识别判断机制呢？discord会返回违禁词的错误，是否会返回对应的错误信息？

**Comment by yklingaOa** [comment]
我尝试发起这样的请求，api一直处于 wait no message found 的状态

**Comment by zcpua** [comment]
use  version v.22 midjourney-api

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/issues/38
