### ISSUE TITLE
改改返回照片地址吧

### ISSUE THREAD

**Issue by china-Charles-yang** [erictik/midjourney-ui#23]
因为网络限制，src="[https://cdn.discordapp.com/attachments/*/nd_the_Ye_18a33ae1-6b56-49a9-9755-6c9d3510f7cf.png"这类照片不能访问，这个怎么处理]([https://cdn.discordapp.com/attachments/*/nd_the_Ye_18a33ae1-6b56-49a9-9755-6c9d3510f7cf.png，你可以把后端显示的代码地址https://cdn.discordapp.com/attachments，可以变成后端可配置？

**Comment by china-Charles-yang** [comment]
改地址对你来说很方便，直接搞个镜像，也很快的

**Comment by zcpua** [comment]
??

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-ui/commit/10a7a38e7cef3947515f74e5114aa71976d3a800
