### ISSUE TITLE
这个地方的tar包，是镜像？

### ISSUE THREAD

**Issue by china-Charles-yang** [erictik/midjourney-ui#25]
![1684462078123](https://github.com/erictik/midjourney-ui/assets/12854076/72ff3a9d-aeb0-46b2-ab38-0d0d7ce77f25)
这个地方的tar包，是镜像？

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-ui/blob/main/.env.example

**Comment by china-Charles-yang** [comment]
我看到了，我之前拉你的项目是通过hub_docker获取的，你后期把项目包放在了那个位置，我想知道，这个是你已经打好的景象包，还是就是文件包而已

**Comment by china-Charles-yang** [comment]
你现在发布的那个的tar.gz包，是直接可以打成镜像的包？

**Comment by zcpua** [comment]
就是代码文件而已

**Comment by zcpua** [comment]
Source code

**Comment by china-Charles-yang** [comment]
你可以帮忙打成镜像？我自己上传tag也行，我不会前端代码做成镜像包
