### ISSUE TITLE
可以把code打成镜像包，大家都可以用

### ISSUE THREAD

**Issue by china-Charles-yang** [erictik/midjourney-ui#26]
![1684462078123](https://github.com/erictik/midjourney-ui/assets/12854076/c7ac4b6a-53cd-498b-a599-bd4db5392a5d)
你可以帮忙打成镜像？我自己上传tag也行，我不会前端代码做成镜像包，拜托了

**Comment by china-Charles-yang** [comment]
就是根据dockerfile,打成镜像包，其实很多人在用你的项目的时候，可能前端都不会写只是部署知道怎么用而已，谢谢了

**Comment by yklingaOa** [comment]
share a docker compose
```bash
version: "1.0"
services:
  mjui:
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: Dockerfile
    image: mjui-image
    container_name: mjui-container
    ports:
      - "3000:3000"
    environment:
      SALAI_TOKEN: ${SALAI_TOKEN}
      SERVER_ID: ${SERVER_ID}
      CHANNEL_ID: ${CHANNEL_ID}
```

**Comment by china-Charles-yang** [comment]
你这个还不是要打镜像嘛，docker build也可以，但是你不确定你打出来的镜像，是否可用，还如直接让作者打镜像，对于他来说，可以就一条命令，

**Comment by china-Charles-yang** [comment]
![1684466192264](https://github.com/erictik/midjourney-ui/assets/12854076/d55ad219-2318-41e5-a2c1-f4f58de501d9)直接自己打镜像包错

**Comment by yklingaOa** [comment]
需要npm run build，.next文件是分 dev 和build环境的， 服务器需要build 包

**Comment by yklingaOa** [comment]
> 你这个还不是要打镜像嘛，docker build也可以，但是你不确定你打出来的镜像，是否可用，还如直接让作者打镜像，对于他来说，可以就一条命令，

compose 已经包含了镜像的构建内容, docker compose up --build -d 就ok了

**Comment by china-Charles-yang** [comment]
> 需要npm run build，.next文件是分 dev 和build环境的， 服务器需要build 包
前端有点不太懂，试了一下，几个包拉不下

**Comment by yklingaOa** [comment]
要先弄清楚它完整的项目构建流程，才能正确的在服务器部署

**Comment by china-Charles-yang** [comment]
> 要先弄清楚它完整的项目构建流程，才能正确的在服务器部署

我也是docker seacrch 慕名而来，其实说实话，真的没有看明白，我其实也是想用一下，没有想到这么麻烦，就是请大佬可以直接给一个镜像包嘛

**Comment by yklingaOa** [comment]
你可以本地测试，npm run build，然后npm run start ，就是运行的build后的.next配置文件的内容。

测试正常之后，rm -rf node_modules，然后把整个项目弄成压缩包放到服务器，在node环境下，运行构建代码就能跑了

**Comment by zcpua** [comment]
> 就是根据dockerfile,打成镜像包，其实很多人在用你的项目的时候，可能前端都不会写只是部署知道怎么用而已，谢谢了

这个项目已经配置了流水线自动 docker build 
https://hub.docker.com/layers/erictik/midjourney-ui/1.1.30/images/sha256-1d7d2fa2de9382535870099b34c045c69947a4ec7d0469364b7b90cbeb7dc202?context=explore
