### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by ti55879** [erictik/midjourney-ui#39]
Error when loading the midjourney ui site seems to be related to the version change as in the main api project

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-ui/commit/e74b0640c81d26f99cc0963a382767778a58b40d

**Comment by adarmanto** [comment]
Did that updates deploy to https://hub.docker.com/r/erictik/midjourney-ui, @zcpua?

I got this error from the latest image:

```
api.DiscordBaseUrl https://discord.com
api.fetchUrl https://discord.com/api/v9/interactions
imagine.error [Error: ImagineApi failed with status 400]
```
But it works when cloning the latest repo. Thanks.

**Comment by artemptushkin** [comment]
@zcpua can you update ui to the latest api version, please? Looks like this is not fixed given that [here](https://github.com/erictik/midjourney-api/issues/118) you write that is in version 3 and we're on the version 2 here
