### ISSUE TITLE
Partial Response Received by API (Netlify & Vercel)

### ISSUE THREAD

**Issue by roblaughter** [erictik/midjourney-ui#41]
Hoping someone can help here because I've spent two days trying to get this working and I'm too dumb to figure out what's wrong. 

I'm trying to generate images via the API endpoint with Make.com, deployed on both Vercel (WS=FALSE) and Netlify(WS=FALSE and WS=TRUE).

The API request often — almost always — returns incomplete streaming binary data which translates into an incomplete JSON response like the below:

{"uri":"https://cdn.discordapp.com/attachments/1099844378522034196/1120457502526554193/grid_0.webp",

Occasionally, it will return the final JSON with progress:done, in a similarly truncated form. Very occasionally, it will return a complete, successful response. 

My timeout values are long enough to fully process the image. 

When I try to generate an image via cURL, I also get incomplete data with the following response:

curl: (18) transfer closed with outstanding read data remaining

Can someone point me in the right direction to even start troubleshooting this? I'm about to lose my mind here.

**Comment by sukbearai** [comment]
I wouldn't use this either.

**Comment by roblaughter** [comment]
> I wouldn't use this either.

I'm open to alternatives.

**Comment by roblaughter** [comment]
Update: I figured out how to use the Node.js client on AWS and it works like a charm. Disregard!
